### ISSUE TITLE
Some villages ID are corrupted

### ISSUE THREAD

**Issue by OlivierTelle** [ecomore2/census#4]
As 103999, 105999

**Comment by choisy** [comment]
In the raw data there are 26 households and 1457 individuals with `Village_ID` 999 and `Enumeration_area_1` 99. They belong to districts 1, 3 and 4. It thus seems that there is not much we can do here except reporting the bug to the _Lao Statistics Bureau_ and hope to receive a corrected version of the data. In the meantime I would suggest you just filter out these observations.
As for `105999`, I can't find such a code in the `census.csv` file. Are you sure about that?

**Comment by OlivierTelle** [comment]
I propose to get rid off these Villages

**Comment by choisy** [comment]
I reopen the issue and will close it when I've effectively done it.

**Comment by choisy** [comment]
Done, `999` villages are deleted.
