### ISSUE TITLE
Q60.2 and Q60.3 are missing

### ISSUE THREAD

**Issue by OlivierTelle** [ecomore2/census#7]
Do you own a car? Do you own a motorbike

**Comment by choisy** [comment]
Check variables `Q60.2._Car.van_Yes`, `Q60.2._Car.van_No`, `Q60.3._MotorBike_0`, `Q60.3._MotorBike_Yes` and `Q60.3._MotorBike_No`. I also added variables `Q60.12._Air_conditioner_0`, `Q60.12._Air_conditioner_Yes` and `Q60.12._Air_conditioner_No`.
